mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('polls.urls')),
     path('',  include('orders.urls')),
    path('',  include('products.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls  import path
from . import views

urlpatterns =  [
    path( '' ,  views.home,  name= 'home'),
]

products/urls.py
from django.urls  import path
from . import views

urlpatterns =  [
    path( 'sweets' ,  views.sweets,  name= 'sweets'),
    path( 'mousse' ,  views.mousse,  name= 'mousse'),
    path( 'sponge' ,  views.sponge,  name= 'sponge'),
    path('product/<product_id>/',  views.product,  name= 'product'),
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
         return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'

class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)  # буквенный тип поля
    price_per_kilogram = models.DecimalField(max_digits=10, decimal_places=0,blank=True, null=True, default=0)  # price * nub
    description = models.TextField(blank=True, null=True, default=None)    #описание
    main_image1 = models.ImageField(upload_to='media/products_images', null=True)
    short_description = models.TextField(blank=True, null=True, default=None, max_length=50)  #описание
    structure = models.TextField(blank=True, null=True, default=None)  # описание
    discount = models.IntegerField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    creted = models.DateTimeField(auto_now_add=True, auto_now=False) #время создания
    updated = models.DateTimeField(auto_now_add=False, auto_now=False)#время обновления




    def __str__(self):
         return "%s" % self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/products_images')
    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    creted = models.DateTimeField(auto_now_add=True, auto_now=False)  # время создания
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)  # время обновления





    # def __str__(self):
    #     return "%s %s" % (self.name, self.email)

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

products/views.py
from django.shortcuts import render
from products.models import *

def sweets(request):
    torts_images = products_images_phones = ProductImage.objects.filter(is_active = True, is_main = True, product__category__id = 1)
    return render(request, 'categories/sweets.html', locals())

def mousse(request):
    torts_images = products_images_phones = ProductImage.objects.filter(is_active = True, is_main = True, product__category__id = 3)
    return render(request, 'categories/mousse cakes.html', locals())

def product(request, product_id):
    product = Product.objects.get(id = product_id)

    return render(request, 'products/product.html', locals())
def sponge(request):
    torts_images = products_images_phones = ProductImage.objects.filter(is_active = True, is_main = True, product__category__id = 2)
    return render(request, 'categories/sponge cakes.html', locals())

templates/products/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="row product-item-row">
        <div class="col-lg-6">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for image in product.productimage_set.all %}
                    <div class="carousel-item" id="product-image">
                        <img src="{{ image.image.url}}" class="d-block w-100" alt="...">
                    </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
                </a>
                  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </a>
            </div>
            <div class="text-center product-price-one product-price">
                                        <h4>Итоговая цена: </h4><h4 class="product_price">{{ product.price_per_kilogram }}.руб</h4>
            </div>
        </div>
        <div class="col-lg-6">
            <h1 class="text-center">
                {{product.name}}
            </h1>
            <div>
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-link nav-description-item active" id="nav-home-tab" data-bs-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Описание</a>
                        <a class="nav-link nav-description-item" id="nav-profile-tab" data-bs-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Состав</a>
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active product-description border-to-description" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab"><p class="product-description">{{ product.description }}</p></div>
                <div class="tab-pane fade product-description border-to-description" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab"><p class="product-description">{{product.structure}}</p></div></div>
            </div>
            <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                            Дополнительный функции
                        </button>
                    </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body accordion-flush">
                        <div class="main-dop-box">
                            <div class="accordion" id="accordionExample">
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingOne">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            Дополнительный функции #1
                                        </button>
                                    </h2>
                                    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <div class="form-check" >
                                                <input class="form-check-input" type="checkbox" id="dop1">
                                                <label class="form-check-label">Доп функция 1</label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="dop2">
                                                <label class="form-check-label">Доп функция 2</label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="dop3">
                                                <label class="form-check-label">Доп функция 3</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingTwo">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                                Дополнительный функции #2
                                        </button>
                                    </h2>
                                    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <div class="form-check">
                                                <input class="form-check-input dop1" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                                                <label class="form-check-label" for="exampleRadios1">
                                                    Без дополнительного оформления
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input dop2" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
                                                <label class="form-check-label" for="exampleRadios2">
                                                    Оформление 1
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input dop3" type="radio" name="exampleRadios" id="exampleRadios3" value="option3">
                                                <label class="form-check-label" for="exampleRadios3">
                                                    Оформление 2
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <div class="select-kilogram">
                <select class="form-select" aria-label="Default select example">
                    <option value="1" selected>1 кг</option>
                    <option value="2">2 кг</option>
                    <option value="3">3 кг</option>
                </select>
            </div>
            <div class="text-center product-price-two product-price">
                    <h4>Итоговая цена: </h4><h4 class="product_price">{{ product.price_per_kilogram }}.руб</h4>
            </div>
            <form id="form_buying_product" class="form-inline" action="{% url 'basket_adding' %}">{% csrf_token %}
<!--              <div class="form-group">-->
<!--                    <input type="number" class="form-control" id = "number">-->
<!--                </div>-->
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-buy btn-lg" id ="submit_btn" data-product_id = "{{ product.id }}" data-product_name = "{{product.name}}" data-price_per_kilogram = "{{product.price_per_kilogram}}">Добавить в корзину</button>
                    </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}